### ISSUE TITLE
Add golangci-lint linter

### ISSUE THREAD

**Issue by barrett-ruth** [nvimdev/guard-collection#10]
Add linter - lints multiple files so diagnostics need to go to proper buffers

**Comment by emrhnpla02** [comment]
I tried to implement this [here](https://github.com/emrhnpla02/guard-collection/commit/27d0a9d59a4c0c1e0f291d8a2366a784ba51dd62), but for some reason, even though it passes the test, it just doesn't work on a real project. I couldn't figure out yet why, but I will look for it more

**Comment by emrhnpla02** [comment]
I just realized that the problem was in my neovim configuration... #28 should work without any trouble
