### ISSUE TITLE
Some tests work locally but not on CI

### ISSUE THREAD

**Issue by xiaoshihou514** [nvimdev/guard-collection#29]
And there's quite a few. No idea why :sweat_smile:

**Comment by barrett-ruth** [comment]
Trying to figure this out, but have never used vusted before - how can I run tests locally? Getting this error now.
<img width="700" alt="image" src="https://github.com/nvimdev/guard-collection/assets/62671086/58a0f20b-b1f4-45bb-8ec2-2cdeaa5263f2">

**Comment by xiaoshihou514** [comment]
@barrett-ruth check out `.github/workflows/test.yml`

**Comment by barrett-ruth** [comment]
Sorry if I'm being dumb... but I sat that? How can I run the tests locally, that workflow command seems to yield an error:

<img width="909" alt="image" src="https://github.com/nvimdev/guard-collection/assets/62671086/77bc8411-6b41-4f77-b709-7fa05c836191">

**Comment by xiaoshihou514** [comment]
Ah, you had the exact same problem as I had 😂
https://github.com/notomo/vusted/issues/12

**Comment by barrett-ruth** [comment]
@xiaoshihou514 after trying and failing to fix this pr for one tool (namely latexindent), I realize this issue would best be debugged using [act](https://github.com/nektos/act). For example, on my system, `latexindent` couldn't simply be run and work immediately - I had to use `sudo cpan -i File::HomeDir` for it to work. Point being, I think the tests are right, but there's a lot of system-specific issues in the CI that must be addressed. 

For example, if you look at the log of my PR, latexindent still doesn't run despite me trying the aforementioned fix. Furthermore, it doesn't have any real error logs in the output, meaning (I think) the command itself is just erroring out and not starting up. This is nearly impossible to debug, but a tool like act would definitely help out. I also fixed up some minor things in the workflow file as well.

I have interviews and exams coming up so I won't have that much time to dedicate to this issue (namely manually debugging and fixing every single individual package). I'll do my best to work on it this week but would also appreciate it if you checked out the pr.

**Comment by xiaoshihou514** [comment]
@barrett-ruth Thanks for doing all these :+1: I've also been distracted by school stuff (and scripting in my dots) lately, but I will try to check it out during weekends.
`act` seems like a life saver, previously I've been waiting five minutes to run one debug session. I will try to sort it out in the future.
