### ISSUE TITLE
Add support for eslint flat configuration 

### ISSUE THREAD

**Issue by dev-737** [nvimdev/guard-collection#38]
Eslint introduced their new [flat config system](https://eslint.org/docs/latest/use/configure/configuration-files-new) around a year ago, meaning `.eslintrc.*` files would instead be `eslint.config.js`, `eslint.config.mjs` or `eslint.config.cjs` files. 

It's more meaningful now that eslint v9 is out in beta, which only supports the flat config system.

**Comment by xiaoshihou514** [comment]
I suppose we just need to change [these lines](https://github.com/nvimdev/guard-collection/blob/main/lua/guard-collection/linter/eslint.lua#L8-L14) and maybe a few flags. But I don't work with js so I wouldn't change it blindly.
Pr is always welcomed though :+1:
